//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luktac.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Luktac.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort convert.
        /// </summary>
        internal static string abort_convert {
            get {
                return ResourceManager.GetString("abort_convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to abort the convertion?.
        /// </summary>
        internal static string abort_convert_msg {
            get {
                return ResourceManager.GetString("abort_convert_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert of selected media is not supported..
        /// </summary>
        internal static string err_msg_convert {
            get {
                return ResourceManager.GetString("err_msg_convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is altered, do you want to play it?.
        /// </summary>
        internal static string err_msg_modified {
            get {
                return ResourceManager.GetString("err_msg_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to play unprotected file?.
        /// </summary>
        internal static string err_msg_unknow {
            get {
                return ResourceManager.GetString("err_msg_unknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert selected media..
        /// </summary>
        internal static string err_title_convert {
            get {
                return ResourceManager.GetString("err_title_convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified file.
        /// </summary>
        internal static string err_title_modified {
            get {
                return ResourceManager.GetString("err_title_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unprotected file.
        /// </summary>
        internal static string err_title_unknow {
            get {
                return ResourceManager.GetString("err_title_unknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to sign the file.
        ///It might the file is locked by another application,
        ///Or is not supported file format or corrupted..
        /// </summary>
        internal static string protect_fail {
            get {
                return ResourceManager.GetString("protect_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is signed.
        /// </summary>
        internal static string protect_success {
            get {
                return ResourceManager.GetString("protect_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing file....
        /// </summary>
        internal static string protect_title {
            get {
                return ResourceManager.GetString("protect_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luktac Media Application.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string validate_error {
            get {
                return ResourceManager.GetString("validate_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to validate file.
        ///Might not supported file format, or the file is corrupted.
        /// </summary>
        internal static string validate_error_msg {
            get {
                return ResourceManager.GetString("validate_error_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is altered..
        /// </summary>
        internal static string validate_msg_modified {
            get {
                return ResourceManager.GetString("validate_msg_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is secured..
        /// </summary>
        internal static string validate_msg_protected {
            get {
                return ResourceManager.GetString("validate_msg_protected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is unprotected..
        /// </summary>
        internal static string validate_msg_unknow {
            get {
                return ResourceManager.GetString("validate_msg_unknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified file.
        /// </summary>
        internal static string validate_title_modified {
            get {
                return ResourceManager.GetString("validate_title_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected file.
        /// </summary>
        internal static string validate_title_protected {
            get {
                return ResourceManager.GetString("validate_title_protected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unprotected file.
        /// </summary>
        internal static string validate_title_unknow {
            get {
                return ResourceManager.GetString("validate_title_unknow", resourceCulture);
            }
        }
    }
}
